#-------------------------------
# General Site Settings

title: Woong
logo: 
author: Gil Woong-Kang
description: gilwoong's blog
email: smostr@gmail.com
phone: 
address: Seongnam-si, Gyeonggi-do, Republic of Korea
copyright: Copyright &copy; 2020 Designed by GilWoong-kang, [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
# - {name: About, link: '/about'}
# - {name: Blog, link: '/blog'}
# - {name: Portfolio, link: '/portfolio'}
# - {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Gil Woong Kang <br> Security & Cloud <br> Engineer

social:
- {icon: "ti-github", link: "https://github.com/gilwoong-kang"}
- {icon: "ti-gmail", link: "smostr@gmail.com"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  안녕하세요! 차세대 IT인을 꿈꾸는 강길웅입니다. 해당 페이지는 저를 소개하는 페이지입니다. 
  저에 대해 궁금하시다면 아래의 컨텐츠들을 둘러봐주세요. 
  저의 개발 행적과 성과, 결과물들을 공유하오니 천천히 둘러봐 주시면 감사하겠습니다. 
  

# blurb-btn-link: '/about'
# blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "현재 1800만 다운로드, 부동산앱 다방에서 API 서버개발을 담당하고 있는 3년차 Java/Spring 백엔드 개발자입니다. 항상 효율적인 비즈니스 로직과 쿼리 성능을 고려하며 버그 없는 서비스를 위해 테스트 코드를 항상 작성하고 있습니다."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "서비스 이해를 위해 비즈니스 도메인 및 프로젝트 별 아키텍처 이해, 서비스 운영을 위한 어드민 활용 이해 등 항상 적극적으로 행동하며 의견을 피력하고 있습니다."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "이로인해 현재는 팀내 점진적 TDD 도입을 이끌었고, 신규 프로젝트 셋팅, 불필요한 내부 어드민 운영방식 개선, 현재 다방 서비스 도메인에 맞춘 면접 과제 및 제출 프로세스 설계, 프로젝트별 소스코드 컨벤션 등의 성과를 냈으며 보다 많은 경험과 성과를 위해 적극적으로 행동하고 있습니다."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Security, color: '#fdb157', value: '70%'}
- {name: Cloud, color: '#9473e6', value: '70%'}
- {name: Develop - Backend, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Bachelor of CS, icon: 'icon-1.png', date: 'Mar 2015 - Feb 2021', organization: 'KOOKMIN UNIV'}
- {name: Cloud / Server, icon: 'icon-2.png', date: 'Dec 2019 - Feb 2020', organization: 'FLYHIGH'}
- {name: Cloud, icon: 'icon-3.png', date: 'Jan 2020 - Jun 2020', organization: 'KOOKMIN UNIV'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Cloud Security Expert Education, date: 'Present', organization: 'SK infosec Academy'}
- {name: Bachelor of CS, date: '2021', organization: 'Kookmin Univ.'}
- {name: Cloud Certificate, date: '2020', organization: 'AWS'}
- {name: High School, date: '2015', organization: 'Seong-il School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

services-title: Services, Project
services:
- {
    name: BankBee,
    icon: ti-palette,
    description: '베트남 시장 대상 금융 어플리케이션 서비스입니다. 본인 계좌를 하나의 어플리케이션에서 보고 조회, 이체 할 수 있는 서비스 입니다. 해당 서비스에서 Cloud, Server Engineer를 담당했습니다.',
    active: # Add true to select section
  }
- {
    name: Moayo,
    icon: ti-vector,
    description: '인스타그램에서 원하는 게시글들을 검색할 수 있도록 한 서비스 입니다. 다중태그 기반으로 태그의 유사도가 높은 게시글들만 찾아서 결과로 보여줍니다. 해당 서비스에서 팀장, Cloud, Server Engineer를 담당했습니다. ',
    active: true # Add true to select section
  }
- {
    name: 클라우드기반 헬스케어시스템 설계,
    icon: ti-panel,
    description: '고객사의 헬스케어 시스템을 클라우드로 이전하고자 새로운 설계를 했던 프로젝트 입니다. 보안적으로 안전하고자 ISMS-P, CSAP 등 인증을 이수할 수 있도록 설계했습니다. 해당 프로젝트에서 팀장, Cloud 설계, Server Engineer를 담당했습니다.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "https://github.com/gilwoong-kang"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "https://github.com/kookmin-sw/capstone-2020-23"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "https://www.notion.so/611d22f4fb6447e8b3b0040c3abc5eff"
    
  # - image : "assets/images/portfolio/item-4.png"
  #   url: "#"
    
  # - image : "assets/images/portfolio/item-5.png"
  #   url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: smostr@email.com

about-image: "assets/images/about/author.jpg"
about-signature: "assets/images/about/signature.png"
about-author: "Johnathan Smith"